from subprocess import Popen

p = Popen('python partnet/test_remote.py --cfg test_configs/l1_bed.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_bag.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_clock.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_earphone.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_faucet.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_bottle.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_bowl.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_door.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_dishwasher.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_display.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_chair.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_lamp.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_storagefurniture.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_hat.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_key.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_knife.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_laptop.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_micro.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_mug.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_refrig.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_scissor.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_trash.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_vase.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l1_table.yaml', shell=True)
p.wait()
print('success')
