from subprocess import Popen

p = Popen('python partnet/test.py --cfg test_configs/l3_bed.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_bag.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_clock.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_earphone.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_faucet.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_bottle.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_bowl.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_door.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_dishwasher.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_display.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_chair.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_lamp.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_storagefurniture.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_hat.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_key.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_knife.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_laptop.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_micro.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_mug.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_refrig.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_scissor.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_trash.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_vase.yaml', shell=True)
p.wait()
p = Popen('python partnet/test.py --cfg test_configs/l3_table.yaml', shell=True)
p.wait()
print('success')
