from subprocess import Popen

p = Popen('python partnet/test_remote.py --cfg test_configs/l2_bed.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_bag.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_clock.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_earphone.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_faucet.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_bottle.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_bowl.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_door.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_dishwasher.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_display.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_chair.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_lamp.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_storagefurniture.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_hat.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_key.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_knife.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_laptop.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_micro.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_mug.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_refrig.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_scissor.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_trash.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_vase.yaml', shell=True)
p.wait()
p = Popen('python partnet/test_remote.py --cfg test_configs/l2_table.yaml', shell=True)
p.wait()
print('success')
